### ISSUE TITLE
Publish to WAPM

### ISSUE THREAD

**Issue by ikanago** [ikanago/omekasy#29]
As @jcaesar mentioned in #27 , we are going to publish `omekasy` to [WAPM](https://wapm.io/).
I'm going to publish to WAPM from GitHub Actions under my name, but I don't know well about Wasm and WAPM.
So could you show me an example of build settings for the Wasm target or provide learning resources or hints, @jcaesar ? 🙏

**Comment by jcaesar** [comment]
There are of course official [docs](https://docs.wasmer.io/ecosystem/wapm/publishing-your-package#creating-an-account-in-wapm) for this.

So far, I haven't bothered automating the process of publishing. My current MO is to fire my own [somewhat hacky build script](https://github.com/jcaesar/wapm-pkg/blob/04560c33e285bfd164f6e9306cffc8834e99525c/waskid.sh), manually create a `wapm.toml`, and locally `wapm publish`.

`wapm.toml` might look like this:
```toml
[package]
name = "ikanago/omekasy"
version = "1.1.0-1"
description = "𝘾𝙤𝙢𝙢𝙖𝙣𝙙 𝙡𝙞𝙣𝙚 𝙖𝙥𝙥𝙡𝙞𝙘𝙖𝙩𝙞𝙤𝙣 𝕥𝕙𝕒𝕥 𝕔𝕠𝕟𝕧𝕖𝕣𝕥𝕤 𝕒𝕝𝕡𝕙𝕒𝕟𝕦𝕞𝕖𝕣𝕚𝕔 𝕔𝕙𝕒𝕣𝕒𝕔𝕥𝕖𝕣𝕤 𝒕𝒐 𝒗𝒂𝒓𝒊𝒐𝒖𝒔 𝒔𝒕𝒚𝒍𝒆𝒔 𝚍𝚎𝚏𝚒𝚗𝚎𝚍 𝚒𝚗 𝚄𝚗𝚒𝚌𝚘𝚍𝚎."
license = "MIT"
repository = "https://github.com/ikanago/omekasy"
readme = "README.md"

[[module]]
name = "omekasy"
source = "omekasy.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "omekasy"
module = "omekasy"
```

Given Github's Rust action has this nifty `cross` flag, it shouldn't be too hard to compile it in GHA. But publishing might require some manual fiddling with putting the wapm login token from a secret to a file somewhere in `~/.…`. I can spend some time figuring that out, if you want me to.
